### ISSUE TITLE
Feature: Generate in bulk

### ISSUE THREAD

**Issue by sks316** [hax0kartik/amiibo-generator#1]
Hey, nice tool you have here. I tried Wumiibo and I like it a lot. I'd like to download all of the amiibo files available on your site, but that could take a while. Why not have an option to generate in bulk, like a "download all" button?

**Comment by Praeses0** [comment]
> Hey, nice tool you have here. I tried Wumiibo and I like it a lot. I'd like to download all of the amiibo files available on your site, but that could take a while. Why not have an option to generate in bulk, like a "download all" button?

Paste+enter this in your browser console
```
var items = document.querySelectorAll("#dataTable > tbody > tr");
for (var i = 0; i < items.length; i++) {
        items[i].click();}
```

**Comment by Praeses0** [comment]
Thank you very much @DanTheMan827 for the bulk ZIP download. 
This is perfect!

**Comment by chimel23** [comment]
> > Hey, nice tool you have here. I tried Wumiibo and I like it a lot. I'd like to download all of the amiibo files available on your site, but that could take a while. Why not have an option to generate in bulk, like a "download all" button?
> 
> Paste+enter this in your browser console
> 
> ```
> var items = document.querySelectorAll("#dataTable > tbody > tr");
> for (var i = 0; i < items.length; i++) {
>         items[i].click();}
> ```

i did and it doesn't work
