### ISSUE TITLE
Credit section: Images are now from AmiiboAPI rather than libamiibo

### ISSUE THREAD

**Issue by My1** [hax0kartik/amiibo-generator#7]
https://github.com/hax0kartik/amiibo-generator/commit/5e799373badb0a2a4dbcf2ed4bd7e2a5d3a61ae9

**Comment by hax0kartik** [comment]
https://github.com/hax0kartik/amiibo-generator/commit/98381eb6212fbb7534082d383df5f85f11be6ce3

**Comment by My1** [comment]
no problem
